homeassistant:
  # Customization file
  customize: !include ../customize/customize.yaml
  customize_domain: !include ../customize/customize_domain.yaml
  customize_glob: !include ../customize/customize_glob.yaml
